/**
 * Database Seed Script for Blueprints
 * Seeds vendors, data type mappings, and default templates
 */

import { storage } from "../storage";
import { 
  defaultVendors, 
  siemensDataTypeMappings, 
  rockwellDataTypeMappings,
  abbDataTypeMappings,
  siemensSCLTemplate,
  rockwellAOITemplate 
} from "./seed-vendors";

export interface SeedResult {
  success: boolean;
  vendors: number;
  dataTypeMappings: number;
  templatePackages: number;
  errors: string[];
}

/**
 * Seed the database with default vendors and configurations
 */
export async function seedDatabase(): Promise<SeedResult> {
  const result: SeedResult = {
    success: true,
    vendors: 0,
    dataTypeMappings: 0,
    templatePackages: 0,
    errors: [],
  };

  const vendorIds: Record<string, string> = {};

  // Seed vendors
  for (const vendorData of defaultVendors) {
    try {
      const existing = await storage.getVendorByName(vendorData.name);
      if (existing) {
        vendorIds[vendorData.name] = existing.id;
        continue;
      }

      const vendor = await storage.createVendor(vendorData);
      vendorIds[vendorData.name] = vendor.id;
      result.vendors++;
    } catch (error) {
      result.errors.push(`Failed to create vendor ${vendorData.name}: ${error}`);
    }
  }

  // Seed Siemens data type mappings
  if (vendorIds["siemens"]) {
    for (const mapping of siemensDataTypeMappings) {
      try {
        await storage.createDataTypeMapping({
          vendorId: vendorIds["siemens"],
          ...mapping,
        });
        result.dataTypeMappings++;
      } catch (error) {
        // Ignore duplicate errors
        if (!String(error).includes("duplicate")) {
          result.errors.push(`Failed to create Siemens mapping: ${error}`);
        }
      }
    }
  }

  // Seed Rockwell data type mappings
  if (vendorIds["rockwell"]) {
    for (const mapping of rockwellDataTypeMappings) {
      try {
        await storage.createDataTypeMapping({
          vendorId: vendorIds["rockwell"],
          ...mapping,
        });
        result.dataTypeMappings++;
      } catch (error) {
        if (!String(error).includes("duplicate")) {
          result.errors.push(`Failed to create Rockwell mapping: ${error}`);
        }
      }
    }
  }

  // Seed ABB data type mappings
  if (vendorIds["abb"]) {
    for (const mapping of abbDataTypeMappings) {
      try {
        await storage.createDataTypeMapping({
          vendorId: vendorIds["abb"],
          ...mapping,
        });
        result.dataTypeMappings++;
      } catch (error) {
        if (!String(error).includes("duplicate")) {
          result.errors.push(`Failed to create ABB mapping: ${error}`);
        }
      }
    }
  }

  // Seed Siemens SCL template
  if (vendorIds["siemens"]) {
    try {
      await storage.createTemplatePackage({
        name: "Siemens SCL Control Module",
        vendorId: vendorIds["siemens"],
        version: "1.0.0",
        description: "Standard SCL Function Block template for Control Modules",
        templateType: "control_module",
        language: "SCL",
        templateContent: siemensSCLTemplate,
        placeholders: [
          { name: "CM_NAME", description: "Control Module name" },
          { name: "VERSION", description: "Version number" },
          { name: "INPUTS", description: "Input variables array" },
          { name: "OUTPUTS", description: "Output variables array" },
          { name: "INOUTS", description: "InOut variables array" },
          { name: "MAIN_LOGIC", description: "Main control logic" },
        ],
        requiredInputs: ["name", "inputs", "outputs"],
      });
      result.templatePackages++;
    } catch (error) {
      if (!String(error).includes("duplicate")) {
        result.errors.push(`Failed to create Siemens template: ${error}`);
      }
    }

    // Siemens Phase template
    try {
      await storage.createTemplatePackage({
        name: "Siemens SCL Phase",
        vendorId: vendorIds["siemens"],
        version: "1.0.0",
        description: "ISA-88 Phase Function Block template with state machine",
        templateType: "phase",
        language: "SCL",
        templateContent: `
// Phase: {{PHASE_NAME}}
// Generated by 0xSCADA Blueprints Engine
// Version: {{VERSION}}
// Date: {{GENERATED_DATE}}

FUNCTION_BLOCK "{{PHASE_NAME}}"
{ S7_Optimized_Access := 'TRUE' }
VERSION : {{VERSION}}

VAR_INPUT
{{#each INPUTS}}
    {{name}} : {{dataType}}; // {{comment}}
{{/each}}
END_VAR

VAR_OUTPUT
{{#each OUTPUTS}}
    {{name}} : {{dataType}}; // {{comment}}
{{/each}}
END_VAR

VAR_IN_OUT
{{#each LINKED_MODULES}}
    {{name}} : {{type}}; // Linked module
{{/each}}
{{#each INOUTS}}
    {{name}} : {{dataType}}; // {{comment}}
{{/each}}
END_VAR

VAR
    CurrentState : Int := 0; // ISA-88 State
    CurrentStep : Int := 0; // Step within state
    StepTimer : Time;
{{#each INTERNAL_VALUES}}
    {{name}} : {{dataType}}; // {{comment}}
{{/each}}
END_VAR

BEGIN
{{MAIN_LOGIC}}
END_FUNCTION_BLOCK
`,
        placeholders: [
          { name: "PHASE_NAME", description: "Phase name" },
          { name: "VERSION", description: "Version number" },
          { name: "LINKED_MODULES", description: "Linked control modules" },
          { name: "INPUTS", description: "Input variables" },
          { name: "OUTPUTS", description: "Output variables" },
          { name: "INTERNAL_VALUES", description: "Internal state variables" },
          { name: "MAIN_LOGIC", description: "State machine logic" },
        ],
        requiredInputs: ["name", "linkedModules"],
      });
      result.templatePackages++;
    } catch (error) {
      if (!String(error).includes("duplicate")) {
        result.errors.push(`Failed to create Siemens phase template: ${error}`);
      }
    }
  }

  // Seed Rockwell AOI template
  if (vendorIds["rockwell"]) {
    try {
      await storage.createTemplatePackage({
        name: "Rockwell AOI Control Module",
        vendorId: vendorIds["rockwell"],
        version: "1.0.0",
        description: "Add-On Instruction template for Control Modules",
        templateType: "control_module",
        language: "AOI",
        templateContent: rockwellAOITemplate,
        placeholders: [
          { name: "CM_NAME", description: "Control Module name" },
          { name: "VERSION", description: "Version number" },
          { name: "INPUTS", description: "Input parameters" },
          { name: "OUTPUTS", description: "Output parameters" },
          { name: "MAIN_LOGIC", description: "Main control logic" },
        ],
        requiredInputs: ["name", "inputs", "outputs"],
      });
      result.templatePackages++;
    } catch (error) {
      if (!String(error).includes("duplicate")) {
        result.errors.push(`Failed to create Rockwell template: ${error}`);
      }
    }

    // Rockwell Structured Text template
    try {
      await storage.createTemplatePackage({
        name: "Rockwell ST Control Module",
        vendorId: vendorIds["rockwell"],
        version: "1.0.0",
        description: "Structured Text routine template for Control Modules",
        templateType: "control_module",
        language: "ST",
        templateContent: `
// {{CM_NAME}} - Structured Text Routine
// Generated by 0xSCADA Blueprints Engine
// Version: {{VERSION}}
// Date: {{GENERATED_DATE}}

// Input Processing
{{#each INPUTS}}
// {{name}} : {{dataType}} - {{comment}}
{{/each}}

// Main Control Logic
{{MAIN_LOGIC}}

// Output Processing
{{#each OUTPUTS}}
// {{name}} : {{dataType}} - {{comment}}
{{/each}}
`,
        placeholders: [
          { name: "CM_NAME", description: "Control Module name" },
          { name: "VERSION", description: "Version number" },
          { name: "INPUTS", description: "Input variables" },
          { name: "OUTPUTS", description: "Output variables" },
          { name: "MAIN_LOGIC", description: "Main control logic" },
        ],
        requiredInputs: ["name", "inputs", "outputs"],
      });
      result.templatePackages++;
    } catch (error) {
      if (!String(error).includes("duplicate")) {
        result.errors.push(`Failed to create Rockwell ST template: ${error}`);
      }
    }
  }

  result.success = result.errors.length === 0;
  return result;
}

/**
 * Check if database has been seeded
 */
export async function isDatabaseSeeded(): Promise<boolean> {
  const vendors = await storage.getVendors();
  return vendors.length > 0;
}
